general:
  region: "ap-southeast-2"
vpc:
  name: "test-vpc-cdk"
  cidr: "10.1.0.0/16"
  subnets:
    - name: "public-cdk"
      cidr: 24
      type: "public"
    - name: "private-cdk"
      cidr: 24
      type: "private"
imagebuilder:
  region: "ap-southeast-2"